fixtures:
  forge_modules:
    xinetd:
      repo: 'puppetlabs/xinetd'
    concat:
      repo: 'puppetlabs/concat'
    stdlib:
      repo: 'puppetlabs/stdlib'
  symlinks:
    "rsync": "#{source_dir}"
