---
fixtures:
  repositories:
    xinetd: 'https://github.com/puppetlabs/puppetlabs-xinetd.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    "rsync": "#{source_dir}"
...
