fixtures:
  repositories:
    "xinetd": "https://github.com/ghoneycutt/puppet-xinetd"
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    "rsync": "#{source_dir}"
