---
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script: "bundle exec rake syntax lint spec SPEC_OPTS='--format documentation'"

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.1.6
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.1.9
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false

